<a href="https://colab.research.google.com/github/kedarvartak/AI_CP/blob/main/numpy-basics-02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy as np


# Array Attributes
1. ndim -
The number of dimensions of an array or Axes is contained in the ndim attribute.
2. shape -
The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
3. size -
total number of elements in array is contained in the size attribute.
4. dtype -
Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
a.ndim

2

In [5]:
a.size

12

In [6]:
a.shape

(3, 4)

In [7]:
a.dtype

dtype('int64')

# How to create a basic array in numpy
- Creating an array filled with zeroes, we use - **np.zeros(number of elements)**
- Creating an array filled with ones, we use - **np.ones(number of elements)**
- Creating an empty array, The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards! - **np.empty(number of elements)**

In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.ones(2)

array([1., 1.])

In [8]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

- Creating an array with range of consecutive elements, we use - **np.range(number of elements)**
- Creating an array with a self defined range with equal gaps, we use - ""np.range(first number, last number, step size)**

## Specifying your datatype
- While default datatype is float, you can specifically state the data type using - np.ones(2, dtype = datatype)


In [4]:
np.arange(4)

array([0, 1, 2, 3])

In [5]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [7]:
np.linspace(0, 10, num=5, dtype = np.int64)

array([ 0,  2,  5,  7, 10])

In [8]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

# Sorting an array
- Sorting an array is simple with np.sort(). You can specify the axis, kind, and order when you call the function.


In [9]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [10]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use:

- argsort, The function in NumPy returns the indices that would sort an array.

- lexsort, which is an indirect stable sort on multiple keys,

- searchsorted, which will find elements in a sorted array, and

- partition, which is a partial sort.

In [11]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [12]:
np.lexsort((arr))

np.int64(0)